# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.

from pathlib import Path

from vqa.check import VQACheck


class VQAException(Exception):
    """Base exception class for VQA-related errors."""

    pass


class MustPassCheckFailedError(VQAException):
    """
    Exception raised when a must-pass VQA check fails validation.

    Attributes:
        vqa_check: The VQACheck object that failed
        actual_answer: The actual answer generated by the model
        video_path: Path to the video that was being tested
        test_config_path: Path to the YAML test configuration file
    """

    def __init__(
        self,
        vqa_check: VQACheck,
        actual_answer: str,
        video_path: str | Path,
        test_config_path: str | Path,
    ) -> None:
        self.vqa_check = vqa_check
        self.actual_answer = actual_answer
        self.video_path = Path(video_path)
        self.test_config_path = Path(test_config_path)

        message = (
            f"Must-pass VQA check failed:\n"
            f"  Video: {self.video_path}\n"
            f"  Config: {self.test_config_path}\n"
            f"  Question: {vqa_check.question}\n"
            f"  Expected: {vqa_check.answer}\n"
            f"  Expected keywords: {vqa_check.keywords}\n"
            f"  Actual: {actual_answer}"
        )
        super().__init__(message)


class ValidationError(VQAException):
    """
    Exception raised when VQA validation fails (non-must-pass checks).

    Attributes:
        vqa_check: The VQACheck object that failed
        actual_answer: The actual answer generated by the model
        found_keywords: List of keywords that were found in the answer
    """

    def __init__(
        self,
        vqa_check: VQACheck,
        actual_answer: str,
        found_keywords: list[str],
    ) -> None:
        self.vqa_check = vqa_check
        self.actual_answer = actual_answer
        self.found_keywords = found_keywords

        message = (
            f"VQA validation failed:\n"
            f"  Question: {vqa_check.question}\n"
            f"  Expected: {vqa_check.answer}\n"
            f"  Expected keywords: {vqa_check.keywords}\n"
            f"  Found keywords: {found_keywords}\n"
            f"  Actual: {actual_answer}"
        )
        super().__init__(message)
